### PR TITLE
#22 my idea

### PR DESCRIPTION
**Pull request by minghu6**
**I modified the OrderedSet (restrict operation) and add class OrderedSetAdapter**
(Every element in OrderedSet consist of both their index and value, so OrderedSet can only interact with OrderedSet. And I write a OrderedSetAdapter base on OrderedSet to interact with Python set, and always return Python set)
    and fix a comment mistake;
    add other Python set method as much as possible; 
    change propery items, ,map to _items, _map

### CODE REVIEW

**Comment by minghu6** [comment]
Tested and Passed on Python27 and Python35, by the way.

**Comment by rspeer** [comment]
I don't understand what all the extra complexity is for. It's fine to maintain your own version of OrderedSet, but what are the benefits of all this additional code to other users?

**Comment by minghu6** [comment]
Because sometimes I want a data struct:
**a Python set, but can record the order of its element** ,so I found this `OrderedSet` .
**The `OrderedSet` lacks some methods,however,it can't behave exactly like a Python set .**
**I can't replace the Python set with this class.**
```python
set1 = {1, 2}
set2 = {2, 3}
#some code...
set3 = set1.difference(set2) #{1}
#############################
set1 = {1, 2}
set2 = {2, 3}

set1 = OrderedSet(set1) #Old OrderedSet
set2 = OrderedSet(set2)
#some code...
set3 = set1.difference(set2) #raise AttributeError: 'OrderedSet' object has no attribute 'difference'
```
As the resaon of above,**I add the other methods which Python set has but `OrderedSet` doesn't.**
**Since ordered set is different from ordinary set after all,I use the OrderedSetAdapter (subclass of OrderedSet) to interact with Python set and itself**. 
```python
set1 = OrderedSetAdapter([1, 2, 3])
set2 = OrderedSetAdapter([3, 2, 1])

set1 & set2 #{1, 2, 3}, OrderedSetAdapter|set op OrderedSet|set => set 
#######################################################################
set1 = OrderedSet([1, 2, 3]) #New OrderedSet
set2 = OrderedSet([3, 2, 1])
set3 = OrderedSet([1, 3, 2])

set1 & set2 #OrderedSet([]) OrderedSet op OrderedSet => OrderedSet
set1 & set3 #OrderedSet([1])
```
Using OrderedSet to interact with itself.Both of two ordered set data struct behaved more exactly like Python set.**EXTRA COMPLEXITY IN CODE FOR MORE COMPATIBILITY AND EASE IN USE.**

**Comment by rspeer** [comment]
There already is a class you can pass an OrderedSet into to perform set operations on it that disregard the order. That class is `set`. OrderedSets are iterable, so they can be passed as the argument to `set`.

I don't see the use case of OrderedSetAdapter, and by breaking compatibility, this PR would interfere with many existing uses of OrderedSet.

Again, please feel free to fork OrderedSet or create your own version if you want it to do things differently.

**Pull request closed without merging**
