### PR TITLE
bumped version in setup.py

### PR DESCRIPTION
**Pull request by Erotemic**
In #30 I bumped the version in the module, but I forgot to bump the version in setup.py.

### CODE REVIEW

**Comment by Erotemic** [comment]
Cool, let me know when the new version is up on pypi, so I can pin one of my projects to this version.

**Comment by rspeer** [comment]
@Erotemic Should I credit you as "Jon Crall" in the readme file?

**Comment by Erotemic** [comment]
Yes, Jon Crall will work.

**Comment by Erotemic** [comment]
@rspeer Any chance you might have time to upload the new version to pypi this weekend? I'm looking to make a new release of ubelt where I offload some of the internal code to standalone modules like these.

**Comment by rspeer** [comment]
Sorry for the delay, it's uploaded now, along with documentation updates.

**Comment by Erotemic** [comment]
Thank you! :smile:

**Pull request merged**
