### PR TITLE
Implement discard and clear methods

### PR DESCRIPTION
**Pull request by Toilal**
I have pushed again the branch with a working implementation, and with more tests to cover the case you have explained earlier.

I understand it's not really performant, but I think it's still better to just make it works for OrderedSet object to have the same features as a standard set object.

### CODE REVIEW

**Comment by rspeer** [comment]
Okay, this looks like a good plan overall. I understand why it would be nice for OrderedSet to support all the set methods.

However, I think it's still incomplete -- isn't this leaving the key that you 'discard' in `self.map`? The removed item will still have an index (which now points to something else) and will still return True in `__contains__`.

**Comment by Toilal** [comment]
True ! I'll fix tomorrow !

**Comment by Toilal** [comment]
It's now fixed, and tested with `in` operator.

**Comment by rspeer** [comment]
Looks good, thanks!

**Pull request merged**
