### PR TITLE
Make package PEP561 compatible

### LINKED ISSUE #72: Package is not PEP 561 compliant
Hi, I notice that this package isn't PEP 561 compliant, making mypy (v0.782, Python 3.7) unable to detect type annotations even though they exist in the code. A remedy is to put a `py.typed` file in the package directory, as explained in https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages. I may be able to make a PR for this, so let me know if you're OK with it.

### PR DESCRIPTION
**Pull request by asford**
Extends #75 with a minor fix to ensure that `py.typed` is included in both sdist and bdist_wheel distributions.
Fixes #72

### CODE REVIEW

**Comment by asford** [comment]
I've manually verified these changes by inspecting the results of `python setup.py bdist_wheel` and `python setup.py sdist`, then installing the wheels.

**Comment by asford** [comment]
@rspeer I *believe* you're the core maintainer here, could I bother you for a review?

**Comment by rspeer** [comment]
PRs related to the packaging of type information have broken this code before. I decided not to merge code related to type checking until the Python ecosystem has a standard way to _test_ that the types work and are packaged correctly. (mypy doesn't test anything; it is a linter.)

**Comment by asford** [comment]
> PRs related to the packaging of type information have broken this code before. I decided not to merge code related to type checking until the Python ecosystem has a standard way to _test_ that the types work and are packaged correctly. (mypy doesn't test anything; it is a linter.)

I don't fully understand this, as there isn't a single standard test framework in the python ecosystem, and certainly not a ecosystem-wide mechanism to test packaging formats other than installing the target package. The "closest" thing to such a standard would likely be a virtualenv/tox based test that installs the package from sdist and wheel, then asserts over the existence of py.typed for the package.

If you want to test the type annotations themselves, I would recommend using pytest_mypy. This is reasonably effective in testing for expected typing results.

**Comment by rspeer** [comment]
Right, I don't just want to test the existence of the file, I want to test that it provides the type information that people are looking for downstream. There has to be a way to verify things besides just merging a packaging change and having people show up to say "you broke type checking in my virtualenv, how dare you".

The intersection of types + packaging in Python is so new and fragile that we're not even close to being able to verify that. The main benefit of programmatically verifying types is that it can be integrated into people's IDEs, and I don't know what this is going to do to anyone else's IDE because I'm not using their IDE.

I know what it's going to do to downstream uses of mypy: before this change, mypy complains about a lot of things and you have to use human judgement to figure out which complaints matter, and after this change, the same situation will remain.

I'm still uninterested in reshaping this package for the sake of one PEP that's a moving target in an ever-changing ecosystem. If they had even thought about the edge case of "a single Python module provides types", I would be more confident in it.

**Comment by rspeer** [comment]
Overall, something I've had to learn over time is that there's no benefit (and lots of costs) to being an early adopter of a technology that you find neither useful nor exciting, and that's PEP 561 for me.

**Pull request closed without merging**
