### PR TITLE
Add .travis.yml file for CI testing.

### PR DESCRIPTION
**Pull request by hayd**
See http://docs.travis-ci.com/user/getting-started/#Step-one%3A-Sign-in.

Here's the [build](https://travis-ci.org/hayd/ordered-set/builds/59445553).

Note: This is an addition to tox, but if you turn it on, it runs the test suite on each commit and for each pull-request (as well as making the testing results public). If you add the repo to [coveralls](https://coveralls.io/), you can also see the coverage for each build.

~~Note2: Unfortunately travis is having an [outage](http://www.traviscistatus.com/incidents/crzxldg09nnr) at the moment (which is quite unusual), hopefully [this build](https://travis-ci.org/hayd/ordered-set/builds/59445553) will (eventually) pass...~~

### CODE REVIEW

**Comment by rspeer** [comment]
Interesting, and thanks.

I'll look into whether we should enable Travis. The publicly visible test status is nice, but other than that it seems a bit redundant, because we already use Jenkins.

**Comment by hayd** [comment]
(Is redundancy a bad thing?)

**Comment by rspeer** [comment]
Y'know, I do think redundancy is a bad thing, when it increases the number of tools we have to use. With this pull request in, I can imagine losing time a year from now with a dev discussion that begins "Hey, it seems something's messed up about our Travis account." "We have a Travis account?"

As it is, ordered-set is already quite thoroughly tested. I can't see it benefiting from a GitHub integration that puts test results on pull requests, because it just doesn't have many pull requests.

I'm sure Travis is a great tool, but it won't do anything for us that we're not already doing.

**Comment by hayd** [comment]
Personally I don't see the logic here, travis is not a tool you have to use... it's passive, but obviously it's up to you.

**Pull request closed without merging**
